add actions for backup and restart
rcatlin/valheim-server-cdk pull request #9
Opened 2021-03-26 01:41 UTC by rdlucas2

2021-03-27 03:46 UTC, rcatlin requested changes
Small comments

2021-03-27 03:46 UTC, rcatlin commented on .github/workflows/backup.yml
> +          comment: Hello world!
Change to:
```
working-directory: /home/ec2-user/
command: ./stop_backup_start.sh
comment: StopBackupStart
```

The script we're using is here: https://github.com/rcatlin/valheim-server-cdk/blob/master/templates/stop_backup_start.sh.hbs

2021-03-27 03:46 UTC, rcatlin commented on .github/workflows/update.yml
> +name: AWS SSM Send-Command Update
Don't need this as of yet.

2021-03-27 03:46 UTC, rcatlin commented on README.md
> +An "easy" way to setup the infrastructure and a running Valheim server (with manual backup capabilities) on AWS!
Let's leave these out of the PR.

I changed the header spelling so please rebase. :+1:

2021-03-27 03:49 UTC, rcatlin commented
Awesome PR, thank you! Just a few small comments and we can get this merged. Excited to get this running.

2021-03-27 03:50 UTC, rcatlin commented
Also, please squash into 1️⃣  commit 

🦑

2021-03-28 01:27 UTC, closed without merging

2021-03-28 01:27 UTC, rdlucas2 commented
Going to update and condense the changes in a new branch.